#!/bin/bash

#SBATCH -p RTXA6Kq
#SBATCH -w node15
#SBATCH --gres=gpu:3
#SBATCH -n 1
#SBATCH -c 12
#SBATCH -o job-tgmad-train-30b-3gpu-%j.output
#SBATCH --time=24:00:00
#SBATCH -J tgmad-train30b

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/export/home3/dazhou/debate-or-vote}"
cd "${REPO_ROOT}"

export OUTPUT_DIR="${OUTPUT_DIR:-out/tg_mad_30b_r1_bs1}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-1}"
export TRAIN_NUM_EPOCHS="${TRAIN_NUM_EPOCHS:-2}"
export TRAIN_SIZE="${TRAIN_SIZE:-10}"
export TRAIN_N_AGENTS="${TRAIN_N_AGENTS:-3}"
export TRAIN_N_ROUNDS="${TRAIN_N_ROUNDS:-1}"
export MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-512}"
export EVALUATOR_MAX_NEW_TOKENS="${EVALUATOR_MAX_NEW_TOKENS:-512}"

export DEBATER_MODEL_NAME="${DEBATER_MODEL_NAME:-Qwen/Qwen3-4B-Instruct-2507}"
export EVALUATOR_MODEL_NAME="${EVALUATOR_MODEL_NAME:-Qwen/Qwen3-30B-A3B-Instruct-2507}"
export EVALUATOR_ENGINE_MODEL="${EVALUATOR_ENGINE_MODEL:-hosted_vllm/Qwen/Qwen3-30B-A3B-Instruct-2507}"

export DEBATER_GPU_SLOTS="${DEBATER_GPU_SLOTS:-0}"
export EVALUATOR_GPU_SLOTS="${EVALUATOR_GPU_SLOTS:-1,2}"
export DEBATER_TENSOR_PARALLEL_SIZE="${DEBATER_TENSOR_PARALLEL_SIZE:-1}"
export EVALUATOR_TENSOR_PARALLEL_SIZE="${EVALUATOR_TENSOR_PARALLEL_SIZE:-2}"

export DEBATER_GPU_MEMORY="${DEBATER_GPU_MEMORY:-0.55}"
export EVALUATOR_GPU_MEMORY="${EVALUATOR_GPU_MEMORY:-0.80}"
export DEBATER_MAX_MODEL_LEN="${DEBATER_MAX_MODEL_LEN:-16384}"
export EVALUATOR_MAX_MODEL_LEN="${EVALUATOR_MAX_MODEL_LEN:-16384}"
export DEBATER_MAX_NUM_SEQS="${DEBATER_MAX_NUM_SEQS:-4}"
export EVALUATOR_MAX_NUM_SEQS="${EVALUATOR_MAX_NUM_SEQS:-1}"

bash "${REPO_ROOT}/scripts/run_tg_mad_train_2gpu.sh"
